### ISSUE TITLE
GarbageCollectorService tries to instantiate processors without constructor data

### ISSUE THREAD

**Issue by michalkleiner** [brettt89/silverstripe-garbage-collector#10]
When running `GarbageCollectorService::inst()->process();`, it collects all collectors and processors as defined by the config.

In https://github.com/brettt89/silverstripe-garbage-collector/blob/master/src/GarbageCollectorService.php#L92 it tries to create singletons of each processor to get their implementor class, but since they define a mandatory constructor param, this fails, e.g. `SQLExpressionProcessor` (https://github.com/brettt89/silverstripe-garbage-collector/blob/master/src/Processors/SQLExpressionProcessor.php#L19) requires an SQLExpression to be provided and similar for others.

There's a couple of options how this can be handled:
1. set the implementor class as a config variable (can't be enforced via interface)
2. change the method to be static so that it doesn't require an object instance
3. use reflection to create an instance without running the constructor method

I can submit a PR if one of the options above is chosen (or a different one is suggested).

**Comment by brettt89** [comment]
Thanks for raising this issue, understand the issue being faced. I had previously used a static method for providing this details in the past, however didn't want to enforce a static abstracted method for the interface (also had some issues with wanting to use injector and calling it etc).

I would probably prefer either Option 3 or something alternative (e.g. Perhaps we can just set a default `SQLExpression = null` and handle errors when not provided and executed).

E.g.
```
public function __construct(SQLExpression $expression = null, string $name = '')
```

Whats your thoughts/preference personally? Happy to be challenged on this as would rather it make sense for use-case rather than intention.

**Comment by michalkleiner** [comment]
I was of two minds on that too, whether to make the constructor params optional (seemed not ideal as they are a requirement of the processor to function) or use the reflection which is on par with using goto and the-likes.

In the end, I probably slightly prefer the optional constructor variable and throwing an exception in methods that require it to be populated.

**Comment by michalkleiner** [comment]
Resolved via https://github.com/brettt89/silverstripe-garbage-collector/pull/11
